import { Ninja, Skill } from '../types';

const mockSkills: Record<string, Skill> = {
  '1': {
    id: '1',
    name: 'Attack',
    desc: 'Basic attack',
    iconId: '1',
    mp: 0,
    cd: 0,
    enterCd: 0,
    isImmediately: 0,
    showIcon: 1,
    ninjutsuLevel: 1,
    ninJutsuTypeList: '',
    jutsuType: [0],
    skillType: 0,
    trigger: 0,
    triggerOnQnt: 0,
    triggerOnRepeat: 0,
    hitPoint: [0],
    closeRefId: 0,
    reaction: [],
    hold: 0,
    Translated: 1
  },
  '100': {
    id: '100',
    name: 'Mystery Skill',
    desc: 'A powerful mystery skill',
    iconId: '100',
    mp: 40,
    cd: 3,
    enterCd: 0,
    isImmediately: 0,
    showIcon: 1,
    ninjutsuLevel: 1,
    ninJutsuTypeList: '',
    jutsuType: [1],
    skillType: 1,
    trigger: 0,
    triggerOnQnt: 0,
    triggerOnRepeat: 0,
    hitPoint: [0],
    closeRefId: 0,
    reaction: [0, 0],
    hold: 0,
    Translated: 1
  }
};

export const mockNinjas: Ninja[] = [
  {
    id: 1,
    name: 'Naruto Uzumaki',
    title: 'Seven Hokage',
    nameDisplay: 'Naruto Uzumaki',
    element: 'Fogo',
    career: 'Ataque',
    power: 12500,
    stats: {
      life: [8500, 9500],
      bodyAtk: [1200, 1400],
      bodyDef: [900, 1100],
      ninjaAtk: [1800, 2000],
      ninjaDef: [1000, 1200]
    },
    level: 6,
    star: 6,
    sex: 1,
    village: 'Konoha',
    properties: ['Uzumaki', 'Jinchuriki', 'Hokage'],
    resistances: {
      fire: 0,
      wind: 0,
      thunder: 0,
      soil: 0,
      water: 0
    },
    img: 'http://tazwanted-naruto.server.live:1040/img/ninjas/head_1.png',
    display: 'http://tazwanted-naruto.server.live:1040/img/ninjas/body_1.png',
    assets: {
      bigImg: '',
      display: '',
      ninja: ''
    },
    ninjaCollection: '1',
    triggers: ['Knockdown'],
    chases: [],
    chasesGen: [],
    mysterySkillId: '100',
    mysterySkillIconId: '100',
    mysterySkillType: 1,
    mysterySkill: mockSkills['100'],
    standardAttackId: '1',
    standardAttackIconId: '1',
    standardAttackSkillType: 0,
    standardAttackSkill: mockSkills['1'],
    chaseSkillIds: [],
    chaseSkillIconIds: [],
    chaseSkillTypes: [],
    chaseSkills: []
  },
  {
    id: 2,
    name: 'Sasuke Uchiha',
    title: 'Last Uchiha',
    nameDisplay: 'Sasuke Uchiha',
    element: 'Raio',
    career: 'Ataque',
    power: 12800,
    stats: {
      life: [8000, 9000],
      bodyAtk: [1300, 1500],
      bodyDef: [850, 1000],
      ninjaAtk: [2000, 2200],
      ninjaDef: [900, 1100]
    },
    level: 6,
    star: 6,
    sex: 1,
    village: 'Konoha',
    properties: ['Uchiha', 'Sharingan'],
    resistances: {
      fire: 0,
      wind: 0,
      thunder: 0,
      soil: 0,
      water: 0
    },
    img: 'http://tazwanted-naruto.server.live:1040/img/ninjas/head_2.png',
    display: 'http://tazwanted-naruto.server.live:1040/img/ninjas/body_2.png',
    assets: {
      bigImg: '',
      display: '',
      ninja: ''
    },
    ninjaCollection: '2',
    triggers: ['High Float'],
    chases: [],
    chasesGen: [],
    mysterySkillId: '100',
    mysterySkillIconId: '100',
    mysterySkillType: 1,
    mysterySkill: mockSkills['100'],
    standardAttackId: '1',
    standardAttackIconId: '1',
    standardAttackSkillType: 0,
    standardAttackSkill: mockSkills['1'],
    chaseSkillIds: [],
    chaseSkillIconIds: [],
    chaseSkillTypes: [],
    chaseSkills: []
  },
  {
    id: 3,
    name: 'Sakura Haruno',
    title: 'Medical Ninja',
    nameDisplay: 'Sakura Haruno',
    element: 'Fisico',
    career: 'Suporte',
    power: 11000,
    stats: {
      life: [9000, 10000],
      bodyAtk: [1000, 1200],
      bodyDef: [1000, 1200],
      ninjaAtk: [1500, 1700],
      ninjaDef: [1200, 1400]
    },
    level: 6,
    star: 6,
    sex: 0,
    village: 'Konoha',
    properties: ['Haruno', 'Medical'],
    resistances: {
      fire: 0,
      wind: 0,
      thunder: 0,
      soil: 0,
      water: 0
    },
    img: 'http://tazwanted-naruto.server.live:1040/img/ninjas/head_3.png',
    display: 'http://tazwanted-naruto.server.live:1040/img/ninjas/body_3.png',
    assets: {
      bigImg: '',
      display: '',
      ninja: ''
    },
    ninjaCollection: '3',
    triggers: ['Repulse'],
    chases: [],
    chasesGen: [],
    mysterySkillId: '100',
    mysterySkillIconId: '100',
    mysterySkillType: 1,
    mysterySkill: mockSkills['100'],
    standardAttackId: '1',
    standardAttackIconId: '1',
    standardAttackSkillType: 0,
    standardAttackSkill: mockSkills['1'],
    chaseSkillIds: [],
    chaseSkillIconIds: [],
    chaseSkillTypes: [],
    chaseSkills: []
  },
  {
    id: 4,
    name: 'Kakashi Hatake',
    title: 'Copy Ninja',
    nameDisplay: 'Kakashi Hatake',
    element: 'Raio',
    career: 'Ataque',
    power: 12200,
    stats: {
      life: [8200, 9200],
      bodyAtk: [1250, 1450],
      bodyDef: [950, 1150],
      ninjaAtk: [1900, 2100],
      ninjaDef: [1050, 1250]
    },
    level: 6,
    star: 6,
    sex: 1,
    village: 'Konoha',
    properties: ['Hatake', 'Sharingan', 'ANBU'],
    resistances: {
      fire: 0,
      wind: 0,
      thunder: 0,
      soil: 0,
      water: 0
    },
    img: 'http://tazwanted-naruto.server.live:1040/img/ninjas/head_4.png',
    display: 'http://tazwanted-naruto.server.live:1040/img/ninjas/body_4.png',
    assets: {
      bigImg: '',
      display: '',
      ninja: ''
    },
    ninjaCollection: '4',
    triggers: ['Knockdown', 'Low Float'],
    chases: [],
    chasesGen: [],
    mysterySkillId: '100',
    mysterySkillIconId: '100',
    mysterySkillType: 1,
    mysterySkill: mockSkills['100'],
    standardAttackId: '1',
    standardAttackIconId: '1',
    standardAttackSkillType: 0,
    standardAttackSkill: mockSkills['1'],
    chaseSkillIds: [],
    chaseSkillIconIds: [],
    chaseSkillTypes: [],
    chaseSkills: []
  },
  {
    id: 5,
    name: 'Itachi Uchiha',
    title: 'Akatsuki Member',
    nameDisplay: 'Itachi Uchiha',
    element: 'Fogo',
    career: 'Ataque',
    power: 13000,
    stats: {
      life: [7500, 8500],
      bodyAtk: [1400, 1600],
      bodyDef: [800, 950],
      ninjaAtk: [2100, 2300],
      ninjaDef: [850, 1000]
    },
    level: 6,
    star: 6,
    sex: 1,
    village: 'Akatsuki',
    properties: ['Uchiha', 'Sharingan', 'Akatsuki'],
    resistances: {
      fire: 0,
      wind: 0,
      thunder: 0,
      soil: 0,
      water: 0
    },
    img: 'http://tazwanted-naruto.server.live:1040/img/ninjas/head_5.png',
    display: 'http://tazwanted-naruto.server.live:1040/img/ninjas/body_5.png',
    assets: {
      bigImg: '',
      display: '',
      ninja: ''
    },
    ninjaCollection: '5',
    triggers: ['High Float', 'Knockdown'],
    chases: [],
    chasesGen: [],
    mysterySkillId: '100',
    mysterySkillIconId: '100',
    mysterySkillType: 1,
    mysterySkill: mockSkills['100'],
    standardAttackId: '1',
    standardAttackIconId: '1',
    standardAttackSkillType: 0,
    standardAttackSkill: mockSkills['1'],
    chaseSkillIds: [],
    chaseSkillIconIds: [],
    chaseSkillTypes: [],
    chaseSkills: []
  }
];

export function getMockNinjas(): Ninja[] {
  return mockNinjas;
}
